#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory


# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

rm -rf 0 > /dev/null

#cp -r 0.anchored 0
cp -r 0.lifted 0
#cp -r 0.blowOff 0


runApplication blockMesh

runApplication -s air extrudeMesh -dict system/extrudeMeshDict.1
runApplication -s fuel extrudeMesh -dict system/extrudeMeshDict.2

runApplication topoSet

runApplication decomposePar

runParallel $(getApplication)

#------------------------------------------------------------------------------
